import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import Sidebar from "../components/Sidebar";
import AuthLoader from "@/components/AuthLoader";

export const metadata: Metadata = {
  title: "My Local Service",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="antialiased sans-serif">
        <AuthLoader />
        <Navbar />

        <div className="flex">
          <Sidebar />

          <main className="flex-1 p-6">
            {children}
          </main>
        </div>

        <Footer />
      </body>
    </html>
  );
}
