import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import { getCurrentUser } from "@/lib/getCurrentUser";
import Sidebar from "../components/Sidebar";
import { IUser } from "@/types";

export const metadata: Metadata = {
  title: "My Local Service",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();
  console.log("Current User in RootLayout:", user);

  return (
    <html lang="en">
      <body className={`antialiased sans-serif`}>
        <Navbar />

        <div className="flex">
          {user && <Sidebar user={user as IUser} />}

          <main className="flex-1 p-6">
            {children}
          </main>
        </div>
        
        <Footer />
      </body>
    </html>
  );
}
